export default {
    'assert': 'https://deno.land/std/node/assert.ts',
    'async_hooks': 'https://deno.land/std/node/async_hooks.ts',
    'buffer': 'https://deno.land/std/node/buffer.ts',
    'child_process': 'https://deno.land/std/node/child_process.ts',
    'cluster': 'https://deno.land/std/node/cluster.ts',
    'console': 'https://deno.land/std/node/console.ts',
    'constants': 'https://deno.land/std/node/constants.ts',
    'crypto': 'https://deno.land/std/node/crypto.ts',
    'dgram': 'https://deno.land/std/node/dgram.ts',
    'diagnostics_channel': 'https://deno.land/std/node/diagnostics_channel.ts',
    'dns': 'https://deno.land/std/node/dns.ts',
    'events': 'https://deno.land/std/node/events.ts',
    'fs': 'https://deno.land/std/node/fs.ts',
    'fs/promises': 'https://deno.land/std/node/fs.ts',
    'http': 'https://deno.land/std/node/http.ts',
    'http2': 'https://deno.land/std/node/http2.ts',
    'https': 'https://deno.land/std/node/https.ts',
    'inspector': 'https://deno.land/std/node/inspector.ts',
    'module': 'https://deno.land/std/node/module.ts',
    'net': 'https://deno.land/std/node/net.ts',
    'os': 'https://deno.land/std/node/os.ts',
    'path': 'https://deno.land/std/node/path.ts',
    'perf_hooks': 'https://deno.land/std/node/perf_hooks.ts',
    'process': 'https://deno.land/std/node/process.ts',
    'punycode': 'https://deno.land/std/node/punycode.ts',
    'querystring': 'https://deno.land/std/node/querystring.ts',
    'readline': 'https://deno.land/std/node/readline.ts',
    'repl': 'https://deno.land/std/node/repl.ts',
    'stream': 'https://deno.land/std/node/stream.ts',
    'stream/promises': 'https://deno.land/std/node/stream.ts',
    'stream/web': 'https://deno.land/std/node/stream.ts',
    'string_decoder': 'https://deno.land/std/node/string_decoder.ts',
    'sys': 'https://deno.land/std/node/sys.ts',
    'timers': 'https://deno.land/std/node/timers.ts',
    'timers/promises': 'https://deno.land/std/node/timers.ts',
    'tls': 'https://deno.land/std/node/tls.ts',
    'trace_events': 'https://deno.land/std/node/trace_events.ts',
    'tty': 'https://deno.land/std/node/tty.ts',
    'url': 'https://deno.land/std/node/url.ts',
    'util': 'https://deno.land/std/node/util.ts',
    'util/types': 'https://deno.land/std/node/util.ts',
    'v8': 'https://deno.land/std/node/v8.ts',
    'vm' : 'https://deno.land/std/node/vm.ts',
    'wasi' :'https://deno.land/std/node/wasi.ts',
    'webcrypto' : 'https://deno.land/std/node/webcrypto.ts',
    'worker_threads' : 'https://deno.land/std/node/worker_threads.ts',
    'zlib' : 'https://deno.land/std/node/zlib.ts',
    'globals' : 'https://deno.land/std/node/globals.ts',
}